# Generated by Django 4.0.6 on 2022-07-22 09:45

from django.db import migrations, models
import myapi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('content', models.FileField(upload_to='', validators=[myapi.validators.validate_file_size, myapi.validators.validate_file_extension])),
                ('uploader', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
