# Generated by Django 4.0.6 on 2022-07-22 16:22

from django.db import migrations, models
import myapi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_videos_delete_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='payment',
            field=models.FloatField(null=True, validators=[myapi.validators.validate_payment]),
        ),
        migrations.AlterField(
            model_name='videos',
            name='content',
            field=models.FileField(upload_to='', validators=[myapi.validators.validate_file_size, myapi.validators.validate_file_extension, myapi.validators.validate_file_extension]),
        ),
    ]
